### ISSUE TITLE
BigQuery suites abort: snowflake-jdbc vendors org.conscrypt, defeating the #1762 exclusion

### ISSUE THREAD

**Issue by hayssams** [starlake-ai/starlake#1786]
## Summary

Every BigQuery integration suite aborts in CI with `NoSuchMethodError` on Conscrypt. The `ExclusionRule("org.conscrypt", "conscrypt-openjdk-uber")` added in #1762 removes the standalone Conscrypt artifact, but **`snowflake-jdbc` vendors 320 `org/conscrypt/*` classes inside its own jar, under the original package name**, where no Maven-level exclusion can reach them. The BigQuery SDK finds that vendored copy, concludes Conscrypt is present, and calls a method it does not have.

This is a regression introduced by the fix in #1762, not the bug that PR set out to solve: #1762's premise is that "the SDK falls back to the default JSSE provider when Conscrypt is absent", which does not hold because Conscrypt is never actually absent.

## Impact

23 suites abort in CI, losing effectively all BigQuery coverage. The run still reports 0 test failures, so the signal is easy to misread as flakiness:

```
Total number of tests run: 878
Suites: completed 154, aborted 23
Tests: succeeded 878, failed 0, canceled 1, ignored 21
```

The exit code 1 comes entirely from the aborted suites.

Beyond CI, any user whose classpath carries both `snowflake-jdbc` and the BigQuery SDK is exposed, which is a normal multi-warehouse Starlake deployment.

## Evidence

Reproduced identically on two `test-only` runs on master, a week apart:

- [run 34046871056](https://github.com/starlake-ai/starflow/actions/runs/34046871056) — 2026-09-06, 47m51s
- [run 34779224296](https://github.com/starlake-ai/starflow/actions/runs/34779224296) — 2026-09-13, 47m

Same error, same first-aborting suite (`TranspileIntegrationBQSpec`):

```
java.lang.NoSuchMethodError: 'void org.conscrypt.Conscrypt.setNamedGroups(javax.net.ssl.SSLSocket, java.lang.String[])'
  at com.google.api.gax.httpjson.HttpJsonConscryptUtils.lambda$configureConscryptSecurityProvider$0(HttpJsonConscryptUtils.java:112)
  at com.google.api.client.http.javanet.ConfigurableSSLSocketFactory.configure(ConfigurableSSLSocketFactory.java:45)
```

Note the first of those runs is ~1h40m **after** #1762 merged (2026-09-06T15:15Z), so the exclusion was already in effect.

## Root cause, verified

The exclusion works — there is no Conscrypt jar on the classpath:

```
$ sbt -batch -error "export Test/fullClasspath" | tr ':' '\n' | grep -i conscrypt
(no output)
```

But scanning every jar on that classpath for the class itself finds one:

```
$ for j in $(... Test/fullClasspath ...); do
    unzip -l "$j" | grep -q "org/conscrypt/Conscrypt\.class" && echo "$j"
  done
snowflake-jdbc-4.3.4.jar
```

It vendors the whole library, unrelocated:

```
$ unzip -l snowflake-jdbc-4.3.4.jar | grep -c "org/conscrypt/"
320
```

and that copy predates the method gax calls:

```
$ javap -classpath . org.conscrypt.Conscrypt | grep -c setNamedGroups
0
```

So: gax probes for `org.conscrypt.Conscrypt`, finds Snowflake's bundled copy, treats Conscrypt as available, and invokes `setNamedGroups` — which exists only in newer Conscrypt releases.

## Suggested fixes

Roughly in order of preference; each needs verifying against the live-BigQuery suites that #1762 used, since this path is not covered by CI (BQ suites cannot run there).

1. **Relocate the vendored package.** Shade `org.conscrypt.**` out of `snowflake-jdbc` so nothing else can discover it. This fixes the assembly, but note it must also hold for the **test** classpath, where sbt-assembly shading does not apply — so this alone may not turn CI green.
2. **Get a Snowflake artifact that does not vendor Conscrypt at `org.conscrypt`.** Snowflake normally relocates its dependencies under `net.snowflake.client.jdbc.internal.*`; Conscrypt sitting at the root package looks like a packaging exception worth checking across versions (currently pinned to `4.3.4` in `project/Versions.scala:47`, with `3.x` also published). A version whose Conscrypt is relocated, or a thin/no-dependencies variant, would remove the collision at the source.
3. **Tell the BigQuery SDK not to use Conscrypt.** If gax exposes a switch to skip the Conscrypt probe, that is the smallest change and is independent of packaging. Needs confirming against the gax version in use.

Whatever is chosen, please also make the failure mode loud: 23 aborted suites currently produce "0 failed" and read like flakes.

## Acceptance

- `test-only` on master reports `aborted 0`.
- The live-BigQuery specs #1762 verified against (`BigQueryBranchSpec`, `SparkParquetToBigQuerySpec`, `TransformIntegration2Spec`) still pass on macOS arm64, i.e. the original JVM-abort bug stays fixed.
- A Starlake project configured for both Snowflake and BigQuery can reach BigQuery in the same JVM.

**Comment by hayssams** [comment]
### Why the guard does not catch this, and why macOS looked fine

`HttpJsonConscryptUtils$ConscryptProviderHolder` calls `org.conscrypt.Conscrypt.newProvider()` as a **direct compile-time reference**, wrapped in a catch that logs:

```
Conscrypt native library unavailable. Falling back to default JDK TLS.
```

So there are three states, not two:

| `org.conscrypt.Conscrypt` on classpath | `newProvider()` | Outcome |
|---|---|---|
| absent | `NoClassDefFoundError` | caught → JDK TLS fallback → **works** (what #1762 assumed) |
| present, native lib missing for this platform | throws | caught → JDK TLS fallback → **works** |
| present, native lib loads, but class is old | **succeeds** | provider used, then `setNamedGroups` → `NoSuchMethodError` → **abort** |

The catch guards provider *creation* only. `setNamedGroups` is called later, per-socket, from `lambda$configureConscryptSecurityProvider$0`, outside any handler.

This explains why #1762 verified green on macOS arm64 while CI is red on Linux. Snowflake's vendored Conscrypt was on the classpath in both cases — the exclusion never removed it. On macOS arm64 the bundled native library presumably does not load, so `newProvider()` throws and the fallback silently works. On Linux CI it loads, the provider is created, and execution reaches the missing method.

Practical consequence: **verifying a fix on macOS proves nothing here.** The check that actually discriminates takes seconds:

```bash
sbt -batch -error "export Test/fullClasspath" | tail -1 > /tmp/cp.txt
for j in $(tr ':' '\n' < /tmp/cp.txt | grep '\.jar$'); do
  unzip -l "$j" 2>/dev/null | grep -q "org/conscrypt/Conscrypt\.class" && echo "$j"
done
```

A fix is correct when that prints nothing, or when the jar it prints contains a Conscrypt that *has* the method:

```bash
javap -classpath . org.conscrypt.Conscrypt | grep -c setNamedGroups   # must be >= 1
```

Either state is safe; the broken state is "present, loadable, and old".

**Comment by hayssams** [comment]
### Upstream has already fixed this — revised plan

This is snowflakedb/snowflake-jdbc#2756 ("Unshaded org.conscrypt 2.5.2 causes JVM crash when combined with Conscrypt 2.6.x"), which is **closed and labelled `status-fixed_awaiting_release`**. The upstream diagnosis matches this one exactly: ~320 unshaded Conscrypt **2.5.2** classes in the `org.conscrypt` namespace while every other bundled dependency is relocated, and the fix is to relocate them under `net.snowflake.client.jdbc.internal.org.conscrypt`.

Worth noting the two symptoms share this single root cause: the macOS arm64 JVM abort that #1762 chased, and the `NoSuchMethodError` here are both "unshaded 2.5.2 meets a caller expecting 2.6.x".

**The fix is not published yet.** Maven Central still has 4.3.4 as `<latest>` and `<release>`, which is the affected version:

```
$ curl -s https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/maven-metadata.xml | grep -E "<latest>|<release>"
  <latest>4.3.4</latest>
  <release>4.3.4</release>
```

So this reduces to a choice between waiting and an interim swap.

**Interim option, verified:** `snowflake-jdbc-thin` publishes the **same 4.3.4 version** and vendors no Conscrypt at all:

```
$ curl -sO https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc-thin/4.3.4/snowflake-jdbc-thin-4.3.4.jar
$ unzip -l snowflake-jdbc-thin-4.3.4.jar | grep -c "org/conscrypt/"
0
```

Being the same version, this is an artifact-variant swap rather than an upgrade — no Snowflake behaviour change to re-qualify. The cost is that the thin jar does not bundle its dependencies, so they must be declared explicitly.

This supersedes the three options in the issue body. Recommended order:

1. **Track the upstream release** and bump `snowflakeJDBC` in `project/Versions.scala:47` when the relocated build ships. Lowest effort, removes the problem at the source, and restores the `ExclusionRule` in build.sbt to doing exactly what #1762 intended.
2. **If CI needs to be green before then**, swap to `snowflake-jdbc-thin` 4.3.4 and add the required transitive dependencies, reverting once (1) lands.

Do not shade in `assembly` alone — it would not fix the test classpath, so CI would stay red. Do not add a modern `conscrypt-openjdk-uber` to win on classpath order — that reintroduces the macOS arm64 abort #1762 removed.

Verification for either path stays the 5-second classpath scan above, not a 47-minute CI run.

**Comment by hayssams** [comment]
### The vendored Conscrypt is unused by Snowflake — removing it is safe

Three checks against `snowflake-jdbc-4.3.4.jar`:

**1. No Snowflake code references it.** All 44,871 classes under `net/snowflake/**` (which includes their relocated internal dependencies) contain zero references:

```
$ unzip -q snowflake-jdbc-4.3.4.jar 'net/snowflake/*'
$ grep -rl "org/conscrypt" net --include=*.class | wc -l
0
```

**2. It is not registered as a JCA provider.** `META-INF/services/java.security.Provider` lists only BouncyCastle, correctly relocated:

```
net.snowflake.client.jdbc.internal.org.bouncycastle.jce.provider.BouncyCastleProvider
net.snowflake.client.jdbc.internal.org.bouncycastle.pqc.jcajce.provider.BouncyCastlePQCProvider
```

**3. Everything else in the jar is relocated.** BouncyCastle, Netty and the rest live under `net.snowflake.client.jdbc.internal.*`. Conscrypt sitting bare at `org.conscrypt` is the anomaly, consistent with upstream treating it as a packaging bug.

So the 320 classes are inert weight for Snowflake and live ordnance for anything else that probes for Conscrypt. Stripping `org/conscrypt/**` does not change Snowflake behaviour.

### The native libraries confirm the platform split

```
META-INF/native/libconscrypt_openjdk_jni-linux-x86_64.so
META-INF/native/libconscrypt_openjdk_jni-osx-x86_64.dylib
META-INF/native/conscrypt_openjdk_jni-windows-x86_64.dll
```

There is **no osx-aarch64 build**. That is exactly why macOS arm64 appears healthy while Linux CI aborts: on arm64 the native library cannot load, `newProvider()` throws, the catch fires, and gax falls back to JDK TLS. On linux-x86_64 it loads, the provider is created, and execution reaches the missing `setNamedGroups`.

Anyone reproducing this should therefore do it on linux-x86_64. A green macOS arm64 run is the bug hiding, not the bug absent.

### Consequence for the fix options

Because removal is provably behaviour-neutral, stripping the classes is a legitimate interim fix alongside the `snowflake-jdbc-thin` swap — but note that stripping must apply to the **test** classpath too, not just `assembly`, or CI stays red. The thin artifact achieves the same end state with no jar rewriting, which is why it remains the lighter interim option.

**Comment by hayssams** [comment]
### Correction: the build-side strip does not reach deployed users

`snowflake-jdbc` is declared `% "provided"` (`project/Dependencies.scala:122`), so it is never bundled into the assembly. Deployments obtain it independently: `Setup.java:470` downloads the jar straight from Maven Central into the install's lib folder,

```java
private static final String SNOWFLAKE_JDBC_VERSION = getEnv("SNOWFLAKE_JDBC_VERSION").orElse("4.3.4");
private static final ResourceDependency SNOWFLAKE_JDBC_JAR = new ResourceDependency(
    "snowflake-jdbc",
    "https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/" + SNOWFLAKE_JDBC_VERSION + "/snowflake-jdbc-" + SNOWFLAKE_JDBC_VERSION + ".jar");
```

and `starlake.sh` puts it on the classpath whenever `ENABLE_SNOWFLAKE` is on (it even infers the flag from `snowflake-jdbc-*.jar` being present, `starlake.sh:96`).

So there are two distinct vectors, and they need different fixes:

| | Source of the jar | Fixed by a `dependencyClasspath` strip? |
|---|---|---|
| CI / `sbt test` | resolved by sbt (`provided` is on the test classpath) | yes |
| A user's install | downloaded by `Setup.java` | **no** |

The strip committed in this repo therefore fixes the 23 aborted CI suites and nothing else. Any user who enables both Snowflake and BigQuery still hits the `NoSuchMethodError` on linux-x86_64. That is a normal multi-warehouse configuration, so the user-facing half is the more important one.

Options for the deployment side, none of them yet applied:

1. **Bump `SNOWFLAKE_JDBC_VERSION` once upstream ships the relocated build.** The real fix; needs no code change beyond the default version, and `Setup.java` already allows overriding it by environment variable.
2. **Strip after download in `Setup.java`**, mirroring what the build now does. Self-contained, but installer changes only reach users through a new release, and it means shipping jar-rewriting logic in the installer.
3. **Download `snowflake-jdbc-thin` plus its dependencies** instead of the fat jar. Removes the vendored copy at the source, at the cost of `Setup.java` having to place several jars where it now places one.

Until one of those lands, the workaround for an affected user is to point `SNOWFLAKE_JDBC_VERSION` at a build whose Conscrypt is relocated, or to remove `org/conscrypt/**` from the downloaded jar by hand.

**Comment by hayssams** [comment]
### Interim fix shipped: repackaged jar served from GitHub Releases

Also worth recording precisely when this broke. Probing every published jar's zip directory shows the relocation was **dropped in 4.0.1**:

| version | `org/conscrypt/*.class` at root | relocated under `net/snowflake/.../org/conscrypt/` |
|---|---|---|
| 3.14.0 – 4.0.0 | 0 | 296 |
| 4.0.1 – 4.3.4 | 296 | 0 |

So every 4.x except 4.0.0 is affected, and downgrading is not an option here: spark-snowflake 3.2.x requires >= 4.0.2.

Interim fix now on master (4d70668b): `Setup.java` downloads a repackaged 4.3.4 with only the 324 Conscrypt entries removed (316 classes + 8 native libs), published as a release asset:

https://github.com/starlake-ai/starflow/releases/tag/deps-snowflake-jdbc-4.3.4-noconscrypt

Chosen over the GitHub Packages Maven registry deliberately: that registry requires authentication even for public packages, which would break `setup` for every end user. Release assets are anonymously downloadable (verified: HTTP 200 without credentials), and `Setup.java` already used this mechanism for other artifacts. The release is marked pre-release so it cannot displace the product release as "Latest".

Only the pinned default version is substituted — overriding `SNOWFLAKE_JDBC_VERSION` still resolves to Maven Central — so this reverts by itself the moment the pin moves to a fixed upstream release.

Verified on the repackaged jar: all 48,790 `net/snowflake` entries preserved, `java.sql.Driver` registration intact, zip valid, and the driver loads and accepts `jdbc:snowflake://` URLs at runtime with `org.conscrypt.Conscrypt` absent.

**Remaining work for this issue:** delete the release asset and revert `Setup.java` (and bump `snowflakeJDBC` in `project/Versions.scala`) once upstream ships the fix. Note the CI-side symptom is untouched by this change — `provided` scope means sbt still resolves the unmodified jar from Maven Central for tests, so the 23 aborted BigQuery suites persist until the version bump.
